server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: 
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "https://localhost:*"
              - "https://127.0.0.1:*"
            allowedMethods: 
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: 
              - "*"
            allowCredentials: true
            exposedHeaders: 
              - "*"
            maxAge: 3600
      discovery:
        locator:
          enabled: false
      loadbalancer:
        enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: # Not used, we use custom decoder
          issuer-uri: # Not used, we use custom decoder

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.pontus.gateway: DEBUG
    org.springframework.security: DEBUG
    root: INFO
